stages:
  - build_develop
  - push_develop
  - deploy_develop

build_develop:
  stage: build_develop
  tags:
    - docker-exec
  script:
    - docker build -t docker.indianic.com/rtf-yilway/python-growthmodel-api-develop:latest .

  only:
    - develop

push_develop:
  stage: push_develop
  tags:
    - docker-exec
  script:
    - docker push docker.indianic.com/rtf-yilway/python-growthmodel-api-develop:latest

  only:
    - develop

deploy_develop:
  stage: deploy_develop
  tags:
    - shell-exec
  script:
    - ssh -o StrictHostKeyChecking=no $USER@$HOST "cd /home/indianic/python_dev && sh deploy.sh"

  only:
    - develop
