stages:
  - build_qa
  - push_qa
  - deploy_qa

build_qa:
  stage: build_qa
  tags:
    - docker-exec
  script:
    - docker build -t docker.indianic.com/rtf-yilway/python-growthmodel-api-qa:latest .

  only:
    - qa

push_qa:
  stage: push_qa
  tags:
    - docker-exec
  script:
    - docker push docker.indianic.com/rtf-yilway/python-growthmodel-api-qa:latest

  only:
    - qa

deploy_qa:
  stage: deploy_qa
  tags:
    - shell-exec
  script:
    - ssh -o StrictHostKeyChecking=no $USER1@$HOST1 "cd /home/indianic/python_qa && sh deploy.sh"

  only:
    - qa
