# Generated by Django 4.0.1 on 2022-02-08 05:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.UUIDField(db_column='userId')),
                ('job_type', models.CharField(choices=[('employee', 'Employee'), ('professional', 'Professional')], db_column='jobType', max_length=30)),
                ('profession_field', models.CharField(db_column='professionField', max_length=255)),
                ('profession', models.CharField(max_length=255)),
                ('compilation_method', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], db_column='compilationMethod', max_length=255)),
                ('current_step', models.IntegerField(db_column='currentStep', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
        ),
        migrations.CreateModel(
            name='GrowthModelActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('growth_model', models.UUIDField(db_column='growthModel')),
                ('skill_type', models.CharField(db_column='skillType', max_length=255)),
                ('activity_type', models.CharField(db_column='activityType', max_length=255)),
                ('activity_id', models.UUIDField(blank=True, db_column='activityId', null=True)),
                ('activity_link', models.TextField(blank=True, db_column='activityLink', null=True)),
                ('activity_title', models.CharField(db_column='activityTitle', max_length=255)),
                ('start_date', models.DateTimeField(blank=True, db_column='startDate', null=True)),
                ('end_date', models.DateTimeField(blank=True, db_column='endDate', null=True)),
                ('alert', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('inProgress', 'In Progress'), ('lost', 'Lost'), ('completed', 'Completed')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('parent_id', models.UUIDField(db_column='parentId', null=True)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
        ),
    ]
