# Generated by Django 4.0.1 on 2022-02-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growthmodel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growthmodelactivity',
            name='growth_model',
        ),
        migrations.RemoveField(
            model_name='growthmodelactivity',
            name='skill_type',
        ),
        migrations.AddField(
            model_name='growthmodelactivity',
            name='growthmodel_id',
            field=models.UUIDField(db_column='growthModelId', default='9c217e9e-2124-484c-912d-b9160fc0acb3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='growthmodelactivity',
            name='skill_area',
            field=models.CharField(db_column='skillArea', default='Hard Skill', max_length=255),
            preserve_default=False,
        ),
    ]
