# Generated by Django 4.0.1 on 2022-02-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growthmodel', '0002_remove_growthmodelactivity_growth_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growthmodelactivity',
            name='end_date',
            field=models.DateField(blank=True, db_column='endDate', null=True),
        ),
        migrations.AlterField(
            model_name='growthmodelactivity',
            name='start_date',
            field=models.DateField(blank=True, db_column='startDate', null=True),
        ),
    ]
