# Generated by Django 4.0.1 on 2022-02-12 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growthmodel', '0003_alter_growthmodelactivity_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='growthmodelactivity',
            old_name='status',
            new_name='activity_status',
        ),
    ]
