# Generated by Django 4.0.1 on 2022-03-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growthmodel', '0005_delete_profession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='growthmodelactivity',
            old_name='growthmodel_id',
            new_name='growth_model_id',
        ),
        migrations.AlterField(
            model_name='growthmodelactivity',
            name='activity_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('inProgress', 'In Progress'), ('lost', 'Lost'), ('completed', 'Completed')], db_column='activityStatus', max_length=30),
        ),
    ]
