# Generated by Django 4.0.1 on 2022-04-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growthmodel', '0007_growthmodelactivity_activity_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growthmodel',
            name='compilation_method',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatic', 'Automatic')], db_column='compilationMethod', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='growthmodel',
            name='job_type',
            field=models.CharField(blank=True, choices=[('employee', 'Employee'), ('professional', 'Professional')], db_column='jobType', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='growthmodel',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='growthmodel',
            name='profession_field',
            field=models.CharField(blank=True, db_column='professionField', max_length=255, null=True),
        ),
    ]
