stages:
  - build_dev
  - push_dev
  - deploy_dev

build_dev:
  stage: build_dev
  tags:
    - docker-exec
  script:
    - docker build -f dockerfile -t docker.indianic.com/rtf-yilway/python-growthmodel-api-dev:latest .

  only:
    - dev

push_dev:
  stage: push_dev
  tags:
    - docker-exec
  script:
    - docker push docker.indianic.com/rtf-yilway/python-growthmodel-api-dev:latest
  only:
    - dev

deploy_dev:
  stage: deploy_dev
  tags:
    - shell-exec
  script:
    - ssh -o StrictHostKeyChecking=no $USER@$HOST "cd /home/indianic/python_dev && sh deploy.sh"

  only:
    - dev
